services:
  - type: web
    name: fme-mobile-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    rootDir: backend
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        sync: false
