services:
  - type: web
    name: fme-mobile-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start-server
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: PORT
        sync: false
